#! /usr/bin/env python
# -*- coding: utf-8 -*-

from reads_for_assembly.generators import SingleReads

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='Generate short reads from contigs')
    parser.add_argument('configuration', metavar = 'CONFIG_FILE',
                                        help = 'Configuration file')

    p = SingleReads(parser.parse_args())
    p.generate()
